
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SONY
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Railway
     */
    public Reservation() {
        super("Railway Reservation System::Reservation Window");
        initComponents();
        setVisible(true);
         setSize(1000,700);
            setLocation(185,20);
            try{
		BufferedImage img=ImageIO.read(getClass().getResourceAsStream("Train.gif"));
		setIconImage(img);
	}catch (Exception e)
	{}
    }
    String usrname;
    public Reservation(String usrname)
     {
         super("Railway Reservation System::Reservation Window");
            initComponents();
            setSize(1000,700);
            setLocation(185,20);
            try{
                	BufferedImage img=ImageIO.read(getClass().getResourceAsStream("Train.gif"));
		setIconImage(img);
	}catch (Exception e)
	{}
            jLabel18.setText(usrname);
              setVisible(true);
              
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Railway Reservation System::Reservation Window");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 102)));
        jPanel1.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel2.setText("From");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 60, 30);

        jLabel3.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 40, 30);

        jLabel4.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel4.setText("Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 50, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 40, 150, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(140, 90, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 300, 90, 30);

        jLabel1.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel1.setText("Ticket Type");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 200, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select", "e-ticket", "i-ticket" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(150, 200, 110, 30);

        jLabel5.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel5.setText("Quota");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 50, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select", "None", "Senior Citizen", "Child" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(150, 250, 140, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 300, 90, 30);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Plan My Travel");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 110, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 0, 120, 20);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(200, 150, 90, 30);

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel5.setLayout(null);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2014" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(120, 150, 70, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox5FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox5FocusGained(evt);
            }
        });
        jPanel5.add(jComboBox5);
        jComboBox5.setBounds(300, 150, 60, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 380, 380);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 200, 380, 380);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("Logout");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9);
        jLabel9.setBounds(870, 10, 60, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(jLabel21);
        jLabel21.setBounds(0, 0, 130, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 990, 40);

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goibibo.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel11);
        jLabel11.setBounds(110, 40, 70, 90);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Booking History");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(90, 140, 130, 17);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/printer.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel13);
        jLabel13.setBounds(400, 40, 110, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cancel.jpg"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel14);
        jLabel14.setBounds(400, 210, 120, 90);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Print Ticket");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel15);
        jLabel15.setBounds(410, 150, 90, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Cancel Ticket");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel16);
        jLabel16.setBounds(420, 310, 100, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refund.jpg"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel17);
        jLabel17.setBounds(90, 180, 120, 120);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Refund");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jLabel20);
        jLabel20.setBounds(120, 310, 70, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(420, 200, 550, 380);

        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel32);
        jLabel32.setBounds(1150, 400, 200, 100);

        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel33);
        jLabel33.setBounds(1150, 270, 200, 100);

        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel34);
        jLabel34.setBounds(1150, 130, 200, 110);
        getContentPane().add(jLabel36);
        jLabel36.setBounds(1000, 640, 80, 30);
        getContentPane().add(jLabel37);
        jLabel37.setBounds(1100, 630, 100, 40);

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setLayout(null);
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 0, 80, 90);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel6.setText("RAILWAY RESERVATION SYSTEM");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(190, 0, 630, 50);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Welcome   Mr.");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(720, 50, 100, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(jLabel18);
        jLabel18.setBounds(830, 50, 140, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1000, 90);

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(null);
        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, -90, 1000, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
     new Login().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String s1=jTextField1.getText();
    String s2=jTextField2.getText();
    String s3=jComboBox1.getSelectedItem().toString();
    String s4=jComboBox2.getSelectedItem().toString();
    String s5=jComboBox3.getSelectedItem().toString();
    String s6=jComboBox4.getSelectedItem().toString();
    String s7=jComboBox5.getSelectedItem().toString();
    String usrname=jLabel18.getText();
        try {
              Class.forName("oracle.jdbc.driver.OracleDriver");
       Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","system");
       Statement st=con.createStatement();
       ResultSet rs=st.executeQuery("select * from railinfo where sourcestation='"+s1+"'and deststation='"+s2+"'");
       if((s1.equals(""))||(s2.equals(""))||s3.equals("--select")||s4.equals("--select")||s5.equals("Year")||s6.equals("Month")||s7.equals("Day")){
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this,"Please Fill Blank Field(s)!!!");}
            
            else if(rs.next())
       {
           new SeatConfirm(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),usrname).setVisible(true);
           
           this.dispose();
       }
        else{
                Toolkit.getDefaultToolkit().beep();
                 JOptionPane.showMessageDialog(this,"Wrong Station code!!!");
                  jTextField1.setText("");
        jTextField2.setText("");
            }
       
        } catch (Exception e) 
        {
            Toolkit.getDefaultToolkit().beep();
                 JOptionPane.showMessageDialog(this,e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
       jComboBox1.removeAllItems();
       jComboBox1.addItem("--select");
       jComboBox1.addItem("e-ticket");
       jComboBox1.addItem("i-ticket");
       jComboBox2.removeAllItems();
       jComboBox2.addItem("--select");
       jComboBox2.addItem("None");
       jComboBox2.addItem("Senior Citizen");
       jComboBox2.addItem("Child");
       jComboBox3.removeAllItems();
       jComboBox3.addItem("Year");
       jComboBox3.addItem("2014");
       jComboBox4.removeAllItems();
       jComboBox4.addItem("Month");
     jComboBox4.addItem("MAY");
                jComboBox4.addItem("JUN");
                jComboBox4.addItem("JUL");
                jComboBox4.addItem("AUG");
                jComboBox4.addItem("SEP");
                jComboBox4.addItem("OCT");
                jComboBox4.addItem("NOV");
                jComboBox4.addItem("DEC");
       jComboBox5.removeAllItems();
       jComboBox5.addItem("Day");
       for(int i=1;i<=9;i++)
           jComboBox5.addItem("0"+i);
           for(int k=0;k<=9;k++)
               jComboBox5.addItem("1"+k);
           for(int k=0;k<=9;k++)
           jComboBox5.addItem("2"+k);
           
               jComboBox5.addItem("30");
               jComboBox5.addItem("31");
           
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox5FocusGained
    String s6=jComboBox4.getSelectedItem().toString();
    if(s6.equals("MAY"))
    {jComboBox5.removeAllItems();
       jComboBox5.addItem("Day");
       jComboBox5.addItem("18");
       jComboBox5.addItem("19");
       for(int i=0;i<=9;i++)
           jComboBox5.addItem("2"+i);
        jComboBox5.addItem("30");
               jComboBox5.addItem("31");
    }  
    if(s6.equals("JUN")||s6.equals("SEP")||s6.equals("NOV")){
    jComboBox5.removeAllItems();
       jComboBox5.addItem("Day");
       for(int i=1;i<=9;i++)
           jComboBox5.addItem("0"+i);
           for(int k=0;k<=9;k++)
               jComboBox5.addItem("1"+k);
           for(int k=0;k<=9;k++)
           jComboBox5.addItem("2"+k);
           
               jComboBox5.addItem("30");
    }
    if(s6.equals("JUL")||s6.equals("AUG")||s6.equals("OCT")||s6.equals("DEC")){
        jComboBox5.removeAllItems();
       jComboBox5.addItem("Day");
       for(int i=1;i<=9;i++)
           jComboBox5.addItem("0"+i);
           for(int k=0;k<=9;k++)
               jComboBox5.addItem("1"+k);
           for(int k=0;k<=9;k++)
           jComboBox5.addItem("2"+k);
           
               jComboBox5.addItem("30");
               jComboBox5.addItem("31");
    }
    }//GEN-LAST:event_jComboBox5FocusGained

    private void jComboBox5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox5FocusLost
     /*if(b=true){
        jComboBox5.removeAllItems();
       jComboBox5.addItem("Day");
       for(int i=1;i<=9;i++)
           jComboBox5.addItem("0"+i);
           for(int k=0;k<=9;k++)
               jComboBox5.addItem("1"+k);
           for(int k=0;k<=9;k++)
           jComboBox5.addItem("2"+k);
           
               jComboBox5.addItem("30");
               jComboBox5.addItem("31");}
          // TODO add your handling code here:*/
    }//GEN-LAST:event_jComboBox5FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               new Reservation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
